@startuml
Connect4 ..> YesNoDialogView
Connect4 ..> GameView
Connect4 : + play()

YesNoDialogView : - question
YesNoDialogView : - answer
YesNoDialogView : -constructor(question)
YesNoDialogView : + read()
YesNoDialogView : + isAffirmative()
YesNoDialogView : + isNegative()

GameView : - board
GameView : - turn
GameView : - boardView
GameView : - turnView
GameView : - constructor()
GameView : - writeResult()
GameView : + play()
GameView *--> Board
GameView *--> Turn
GameView *--> BoardView
GameView *--> TurnView

TurnView : - turn
TurnView *--> Turn
TurnView : - constructor(turn)
TurnView : + configure()
TurnView : + play()
TurnView : + visitRandom(randow)
TurnView : + visitHuman(human)
TurnView : - writeTitle()
TurnView ..> Coordinate

BoardView : - board
BoardView : - constructor(board)
BoardView : + writeln()
BoardView *--> Board
BoardView ..> Coordinate

Turn : + {static} MAX_PLAYERS
Turn : + {static} NUMBER_PLAYER
Turn : - currentTurn
Turn : - players
Turn : - board
Turn *--> Player
Turn *--> Board
Turn : - constructor(board)
Turn : + createPlayers(humanPlayers)
Turn : + getCurrentPlayer()
Turn : + changeTurn()
Turn : + {static} isNumberPlayerValid(number)
Turn ..>  ClosedInterval

Player : - color
Player : - board
Player *--> Color
Player *--> Board
Player : - constructor(color, board)
Player : + getColor()
Player : + isComplete(column)
Player : + dropToken(column)
Player <|-- Human
Player <|-- Random

Human : - constructor(playerNumber, board)
Human : + dropToken(column)
Human : + accept(turnView)
Human ..> Coordinate

Random : - constructor(playerNumber, board)
Random : + dropToken()
Random : + accept(turnView)
Random ..> Coordinate

Color : + {static} RED
Color : + {static} YELLOW
Color : - string
Color : - constructor(string)
Color : + toString()
Color : + {static} get(ordinal)
Color : - {static} values()

Board : + {static} LINE_LENGTH
Board : - EMPTY_CELL
Board : - cells
Board : - currentCoordinate
Board : - constructor()
Board : - calculateRow(column)
Board : - getLine(initialCoordinate, direction)
Board : - isConnect4(line)
Board : + getColor(coordinate)
Board : + dropToken(column, color)
Board : + isComplete(column)
Board : + isWinner()
Board ..> Direction
Board ..> Coordinate

Direction : + {static} SOUTH
Direction : + {static} WEST
Direction : + {static} SOUTH_WEST
Direction : + {static} NORTH_WEST
Direction : - coordinate
Direction *--> Coordinate
Direction : - constructor(row, column)
Direction : + getCoordinate() 
Direction : + getOppocite()
Direction : + {static} values()

Coordinate : + {static} MAX_ROWS
Coordinate : + {static} NUMBER_ROWS
Coordinate : + {static} MAX_COLUMNS
Coordinate : + {static} NUMBER_COLUMNS
Coordinate : - row
Coordinate : - column
Coordinate : - constructor(row, column)
Coordinate : + getRow()
Coordinate : + getColumn()
Coordinate : + getShifted(coordinate)
Coordinate : + {static} isRowValid(row)
Coordinate : + {static} isColumnValid(column)
Coordinate ..>  ClosedInterval

ClosedInterval : - min
ClosedInterval : - max
ClosedInterval : - constructor(min, max)
ClosedInterval : + isIncluded(value)

@enduml