@startuml
Connect4 ..> YesNoDialogView
Connect4 ..> GameView
Connect4 : + init()
Connect4 : - askGameMode()
Connect4 ..> PlayerView
Connect4 ..> CPU

YesNoDialogView : - question
YesNoDialogView : - answer
YesNoDialogView : + read()
YesNoDialogView : + isAffirmative()
YesNoDialogView : + isNegative()

CPU : + readToken()
CPU ..>Token

PlayerView : + readToken()
PlayerView ..>Token

GameView : - players
GameView *--> Game
GameView : + play()
GameView : - showBoard()
GameView : - showFinalMsg()

Game : - MAX_TURNS
Game : - currentToken
Game *--> Board
Game *--> Turn
Game : + getBoardLength()
Game : + getBoardRow(number)
Game : + getTurn()
Game : + getPlayer()
Game : + changeTurn() {
Game : + addToken(token)
Game : + calculateRow(col)
Game : + isWinner()
Game : + isTied()

Board : - MIN_ROWS
Board : - MIN_COLUMNS
Board : - MAX_ROWS
Board : - MAX_COLUMNS
Board : - TOKENS_CONNECTED_FOR_WIN
Board : - grid
Board : + getLength() 
Board : + getRow(number) {
Board : + calculateRow(col)
Board : + addToken(token) {
Board : + isConnectedInVertical(token)
Board : + isConnectedInHorizontal(token)
Board : + isConnectedInDiagonal(token)

Turn : - numberOfRounds
Turn : - PLAYER_1
Turn : - PLAYER_2
Turn : + getPlayer()
Turn : + getTurns()
Turn : + getTurn()
Turn : + changeTurn()

Token : + row
Token : + col
Token : + player

@enduml