@startuml
Connect4 ..> YesNoDialogView
Connect4 ..> Game
Connect4 ..> GameView
Connect4 : + play()

YesNoDialogView : - question
YesNoDialogView : - answer
YesNoDialogView : + read()
YesNoDialogView : + isAffirmative()
YesNoDialogView : + isNegative()

GameView : + play()
GameView *--> PlayerView
GameView *--> BoardView

PlayerView : + putToken()
PlayerView ..> Coordinate

BoardView : + showBoard()

Game : - currentCoordinate
Game *--> Board
Game *--> Turn
Game : + getBoard()
Game : + getColor()
Game : + changeTurn() {
Game : + addToken(coordinate)
Game : + calculateRow(col)
Game : + isWinner(currentCoordinate)
Game : + isTied()

Board ..> Line
Board : - EMPTY_CELL
Board : + MAX_ROWS
Board : + MAX_COLUMNS
Board : - cells
Board : - TOKENS_CONNECTED_FOR_WIN
Board : + getCell(coordinate)
Board : - isConnect4(direction)
Board : + calculateRow(col)
Board : + addToken(coordinate, color)
Board : + isWinner(currentCoordinate)

Turn : - numberOfRounds
Turn : + MAX_TURNS
Turn : - COLORS
Turn : - getTurn()
Turn : + getColor()
Turn : + changeTurn()
Turn : + isFinished()

Line *--> Coordinate
Line : + getLine()
Line : + getOppocite()

Coordinate : - x
Coordinate : - y
Coordinate : + shift()

@enduml