@startuml
Connect4 ..> YesNoDialogView
Connect4 ..> Game
Connect4 ..> GameView
Connect4 : + play()

YesNoDialogView : - question
YesNoDialogView : - answer
YesNoDialogView : + read()
YesNoDialogView : + isAffirmative()
YesNoDialogView : + isNegative()

GameView : + play()
GameView *--> PlayerView
GameView *--> BoardView

PlayerView : + putToken()
PlayerView ..> Coordinate

BoardView : + showBoard()

Game *--> Board
Game *--> Turn
Game *--> Checker
Game : + getBoard()
Game : + getColor()
Game : + changeTurn() {
Game : + addToken(coordinate)
Game : + calculateRow(col)
Game : + isWinner()
Game : + isTied()

Board : - EMPTY_CELL
Board : + MAX_ROWS
Board : + MAX_COLUMNS
Board : - cells 
Board : - initCells()   
Board : + getCell(coordinate)
Board : + calculateRow(col)
Board : + addToken(coordinate, color)

Turn : - numberOfRounds
Turn : + MAX_TURNS
Turn : - COLORS
Turn : - getTurn()
Turn : + getColor()
Turn : + changeTurn()
Turn : + isFinished()

Checker : - currentToken
Checker : - TOKENS_CONNECTED_FOR_WIN
Checker : + setCurrentToken(token)
Checker : - isConnect4(direction, board)
Checker : + isWinner(board)
Checker ..> Line

Line *--> Coordinate
Line : + getLine()
Line : + getOppocite()

Coordinate : - x
Coordinate : - y
Coordinate : + shift()

@enduml